"""
extract_checklist.py
---------------------
Extract the fields Eric needs from a ZwickRoell "Order Report / Checklist" .docx.

The Checklist is auto-generated by the ERP with a FIXED table layout; only the
values change between orders. We therefore locate each field by its LABEL within
the relevant table (resilient to row shifts) rather than by hard-coded indices or
by colour. (The red highlighting in the sample was only a spec telling us which
fields matter; production files are not highlighted.)

Usage:
    python extract_checklist.py "C:\\path\\to\\Checklist ....docx"
    # prints the normalized field dict as JSON
"""
from __future__ import annotations

import glob
import json
import os
import re
import sys

import docx


# --------------------------------------------------------------------------- #
# Low-level table helpers
# --------------------------------------------------------------------------- #
def _cell_text(cell) -> str:
    """Cell text with internal line breaks normalised to ' / '."""
    return cell.text.strip().replace("\r", "").replace("\n", " / ").strip()


def _norm(s: str) -> str:
    """Normalise a label for tolerant matching."""
    return re.sub(r"\s+", " ", (s or "")).strip().lower().rstrip(":")


def find_value_in_row_table(table, label, value_offset=1):
    """For 'label | value' style tables: find the row whose first cell matches
    `label`, return the cell `value_offset` columns to the right. Handles tables
    that pack two label/value pairs per row by scanning every cell."""
    target = _norm(label)
    for row in table.rows:
        cells = row.cells
        for ci, cell in enumerate(cells):
            if _norm(_cell_text(cell)) == target and ci + value_offset < len(cells):
                val = _cell_text(cells[ci + value_offset])
                # skip when the "value" is just the merged label repeated
                if _norm(val) != target:
                    return val
    return None


def find_value_right_block(table, label):
    """Table 3 style: left pair is c0=label / c1=value; right pair is
    c3..c5=label (merged) / c6=value. Search any cell for the label and return
    the next distinct non-empty cell on that row."""
    target = _norm(label)
    for row in table.rows:
        cells = [_cell_text(c) for c in row.cells]
        for ci, txt in enumerate(cells):
            if _norm(txt) == target:
                for nxt in cells[ci + 1:]:
                    if _norm(nxt) and _norm(nxt) != target:
                        return nxt
    return None


# --------------------------------------------------------------------------- #
# Field-specific parsing
# --------------------------------------------------------------------------- #
def parse_header(tables):
    """Table 0 single banner: 'ORD... / acct / customer /'."""
    if not tables:
        return {}
    parts = [p.strip() for p in _cell_text(tables[0].rows[0].cells[0]).split("/")]
    parts = [p for p in parts if p]
    out = {}
    if parts:
        out["order_id"] = parts[0]
    if len(parts) > 1:
        out["account_no"] = parts[1]
    if len(parts) > 2:
        out["customer_name"] = parts[2]
    return out


def parse_ship_to(tables):
    """Table 2: the 'Ship to' column (index 2). Returns address + shipping contact."""
    out = {}
    if len(tables) < 3:
        return out
    t = tables[2]
    # column index 2 holds the Ship-to block in row 1
    block = _cell_text(t.rows[1].cells[2])
    # split off contact
    m = re.search(r"Shipping Contact:\s*(.*)", block)
    if m:
        out["shipping_contact"] = m.group(1).strip(" /")
        block = block[: m.start()].strip(" /")
    out["ship_to_address"] = block.strip(" /")
    # drop a leading "Account No.: ..." segment if present
    out["ship_to_address"] = re.sub(
        r"^Account No\.?:?\s*\S+\s*/?\s*", "", out["ship_to_address"]
    ).strip(" /")

    # Technical Contact lives further down the same column (row 4)
    if len(t.rows) > 4:
        tech = _cell_text(t.rows[4].cells[2])
        m = re.search(r"Technical Contact:\s*(.*)", tech)
        if m:
            out["technical_contact"] = m.group(1).strip(" /")
    return out


def parse_summary(tables):
    """Table 3: many label/value pairs (left c0->c1, right c3..c5->c6)."""
    out = {}
    if len(tables) < 4:
        return out
    t = tables[3]
    mapping = {
        "order_date": "Order Date",
        "dossier_no": "Dossier No.",
        "machine_type": "Machine Type",
        "industry": "Industry",
        "po_received_on": "PO received on:",
        "customer_delivery_date_zru_oc": "Customer Delivery Date ZRU OC:",
        "eta_for_sa": "ETA for SA:",
    }
    for key, label in mapping.items():
        val = find_value_right_block(t, label)
        if val:
            out[key] = val
    return out


def parse_order_processing(tables):
    """Table 4: c0=label / c1=value (left), c2=label / c3=value (right)."""
    out = {}
    if len(tables) < 5:
        return out
    t = tables[4]
    mapping = {
        "send_po_to_zrx": "Send PO to ZRX",
        "send_order_acknowledgement": "Send Order Acknowledgement",
        "received_oc_from_zrx": "Received OC from ZRX",
        "oc_sent_to_customer": "OC sent to Customer",
        "packing_details_from_zrx": "Packing Details from ZRX",
        "collection_order_to_forwarder": "Collection Order to Forwarder",
        "information_customer_cia": "Information Customer w. CIA",
        "invoice_received_from_zrx": "Invoice received from ZRX",
        "iqoq": "IQ/OQ n",
    }
    for key, label in mapping.items():
        out[key] = find_value_in_row_table(t, label, value_offset=1)
    return {k: v for k, v in out.items() if v}


def parse_service(tables):
    """Table 5: c0=label / c1=value."""
    out = {}
    if len(tables) < 6:
        return out
    t = tables[5]
    mapping = {
        "installation_required_hours": "Installation Required / Hours",
        "special_cal_gear_required": "Special Cal Gear Required",
        "technician": "Technician",
        "service_activity_done_by": "Service Activity done by",
        "sa": "SA",
    }
    for key, label in mapping.items():
        out[key] = find_value_in_row_table(t, label, value_offset=1)
    return {k: v for k, v in out.items() if v}


# --------------------------------------------------------------------------- #
# Public API
# --------------------------------------------------------------------------- #
def extract(docx_path: str) -> dict:
    doc = docx.Document(docx_path)
    tables = doc.tables
    data: dict = {"source_file": os.path.basename(docx_path)}
    data.update(parse_header(tables))
    data.update(parse_ship_to(tables))
    data.update(parse_summary(tables))
    data.update(parse_order_processing(tables))
    data.update(parse_service(tables))
    return data


def find_checklist(folder: str) -> str | None:
    """Return the first Checklist*.docx in `folder` (non-temp)."""
    hits = [
        p
        for p in glob.glob(os.path.join(folder, "Checklist*.docx"))
        if not os.path.basename(p).startswith("~$")
    ]
    return hits[0] if hits else None


def main(argv):
    if len(argv) > 1:
        path = argv[1]
    else:
        path = find_checklist(os.path.dirname(os.path.abspath(__file__)))
    if not path or not os.path.exists(path):
        print(f"ERROR: checklist file not found: {path}", file=sys.stderr)
        return 4
    data = extract(path)
    print(json.dumps(data, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
